### ISSUE TITLE
[PE-D][Tester D] Improper break of bullet points

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F10-3/tp#120]
![e325ddcc42b4a8196f97fe057b9b9ec.png](https://raw.githubusercontent.com/siqirua/ped/main/files/f13edc93-860f-4d2c-b1d1-ab41af0614ec.png)

Improper break of bullet points in 'Notes about the command format' section. The two points in the screenshot should be considered as one point instead of two separate points.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: siqirua/ped#1

**Comment by TohLiYuan** [comment]
Fixed in #160
