### ISSUE TITLE
[PE-D][Tester C] UG does not contain what units are accepted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F10-3/tp#126]
UG does not tell the user what units is accepted by the command, thus I cannot properly use the functions as some units that I thought can be put in, such as Oz, ml, L, was not accepted as proper units. 

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: owenyeo/ped#2

**Comment by TohLiYuan** [comment]
Duplicate of #123
