### ISSUE TITLE
[PE-D][Tester C] Can add multiple ingredients in a single line in recipe

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F10-3/tp#137]
![image.png](https://raw.githubusercontent.com/owenyeo/ped/main/files/68af7f4c-8c72-408e-8387-6aa67a7e6772.png)

I seem to be able to add multiple valid ingredients in a single line here. 

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: owenyeo/ped#7

**Comment by TohLiYuan** [comment]
The ingredients are not actually added as is, rather it is parsed as:
```
Name: Water 100g Flour
Quantity: 1.0
Unit: KILOGRAM
```
A good QoL change would be to separate these separately for parsing or warn the user about it, but it is currently not in the scope of the version release
