### ISSUE TITLE
[PE-D][Tester A] Stock command not working as intended

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F10-3/tp#159]
As brought up in the user guide, for `Bay Leaves`, typing the command `stock leaves` will not yield any result containing bay leaves, yet it does

**User Docs**

![image.png](https://raw.githubusercontent.com/Sebtey/ped/main/files/4c793305-ae96-4759-aaab-8548dcea845d.png)

**Before**

![image.png](https://raw.githubusercontent.com/Sebtey/ped/main/files/a2675c78-377a-4f2f-8ad5-d00317474735.png)

**After**

![image.png](https://raw.githubusercontent.com/Sebtey/ped/main/files/814735bd-26b0-47e6-954c-6c9b21853995.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Sebtey/ped#8

**Comment by TohLiYuan** [comment]
This is the intended behaviour as stock uses partial matching. Thus searching for `Leaves` will show both `Bay Leaves` and `Leaves` as they both contain the keyword `Leaves`

The UG suggests that searching for `Bay` will show `Bay Leaves` but not `Leaves`, although the UG could be phrased better to improve readability.

**Comment by TohLiYuan** [comment]
Ammended in #160
