### ISSUE TITLE
MarkBind Docs issue

### ISSUE THREAD

**Issue by tlylt** [AY2324S1-CS2103T-F10-3/tp#2]
Hi Team (@prawnzyy),

I'm a MarkBind dev checking in to see if the MarkBind docs branch is working well for CS2103T students. I noticed that even though you have updated the repo name in docs.yml, the published site seems to have some issues due to incorrect baseUrl.
- https://ay2324s1-cs2103t-f10-3.github.io/tp/
- The problem is that some web assets are not fetched correctly, hence the rendering is incorrect

**You will need to update the baseUrl in docs.yml to '/tp' (the actual name of this github repo), instead of your organization name to make the reference work as expected when published via GitHub pages. That will make the rendering work.**
![image](https://github.com/AY2324S1-CS2103T-F10-3/tp/assets/41845017/745c77c4-d40f-4c46-8a76-0bf8619ba4cc)

To this:
![image](https://github.com/AY2324S1-CS2103T-F10-3/tp/assets/41845017/c75b4d8d-e993-4b54-8ddb-daaa72c202b3)

cc @damithc

**Comment by prawnzyy** [comment]
Ok sure, I have made the necessary changes. Do let us know if the issue still persists. Thank You!

**Comment by tlylt** [comment]
> Ok sure, I have made the necessary changes. Do let us know if the issue still persists. Thank You!

Looks like the link is working now, great job!
